/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTransactionsSplatRouteImport } from './routes/api/transactions.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsSplatRoute = ApiTransactionsSplatRouteImport.update({
  id: '/api/transactions/$',
  path: '/api/transactions/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/transactions/$': typeof ApiTransactionsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/transactions/$': typeof ApiTransactionsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/transactions/$': typeof ApiTransactionsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/transactions/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/transactions/$'
  id: '__root__' | '/' | '/api/transactions/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTransactionsSplatRoute: typeof ApiTransactionsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/$': {
      id: '/api/transactions/$'
      path: '/api/transactions/$'
      fullPath: '/api/transactions/$'
      preLoaderRoute: typeof ApiTransactionsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTransactionsSplatRoute: ApiTransactionsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
